use "pony_test"
use "pony_check"

actor \nodoc\ Main is TestList
  new create(env: Env) =>
    PonyTest(env, this)

  fun tag tests(test: PonyTest) =>
    test(_TestCellCreate)
    test(_TestCellDefaults)
    test(_TestCellEq)
    test(_TestCellAttrs)
    test(_TestCellWideContinuation)
    test(Property1UnitTest[CellTuple](_PropCellRoundtripEq))
    test(_TestGridCreate)
    test(_TestGridDimensionMismatch)
    test(_TestGridApply)
    test(_TestGridOutOfBounds)
    test(_TestGridFilled)
    test(Property1UnitTest[_GridAccessSample](_PropGridAccessValid))
    test(_TestPackerSingleChild)
    test(_TestPackerTwoChildrenHorizontal)
    test(_TestPackerTwoChildrenVertical)
    test(_TestPackerPadding)
    test(_TestPackerExpand)
    test(_TestPackerExpandNoFill)
    test(_TestPackerFromEnd)
    test(_TestPackerOverflow)
    test(Property1UnitTest[_PackerSample](_PropPackerTotalFitsContainer))
    test(Property1UnitTest[_PackerExpandSample](_PropPackerExpandFillsExactly))
    test(_TestParserPrintableChar)
    test(_TestParserEnter)
    test(_TestParserEscape)
    test(_TestParserTab)
    test(_TestParserBackspace)
    test(_TestParserCtrlA)
    test(_TestParserArrowUp)
    test(_TestParserArrowDown)
    test(_TestParserArrowRight)
    test(_TestParserArrowLeft)
    test(_TestParserHome)
    test(_TestParserEnd)
    test(_TestParserDeleteKey)
    test(_TestParserF1)
    test(_TestParserUtf8TwoByte)
    test(_TestParserUtf8ThreeByte)
    test(_TestParserMultipleChars)
    test(_TestEncoderMoveTo)
    test(_TestEncoderSetFg)
    test(_TestEncoderSetBg)
    test(_TestEncoderSetAttrs)
    test(_TestEncoderResetAttrs)
    test(_TestEncoderWriteChar)
    test(_TestEncoderWriteUtf8)
    test(_TestEncoderHideCursor)
    test(_TestEncoderShowCursor)
    test(_TestEncoderClearScreen)
    test(_TestDifferIdenticalFrames)
    test(_TestDifferAllChanged)
    test(_TestDifferSingleChange)
    test(_TestDifferEmptyPrevious)
    test(Property1UnitTest[_DifferSample](_PropDifferIdenticalZeroChanges))
    test(Property1UnitTest[_DifferSample](_PropDifferFullChangeCount))
